### ISSUE TITLE
Python 3.6 or 3.8 error

### ISSUE THREAD

**Issue by andygr** [vincentbernat/video2hls#5]
Hello,

I have the following Ubuntu:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial 
```

and Python 3.6.10 (also tried with 3.8)

but when I am trying to execute it I am getting this error:

```
File "./video2hls", line 305
    jargs.append(f'`{arg}`')
                          ^
SyntaxError: invalid syntax
```
Do I need to change the ' to something else?

Thanks
Andrew

**Comment by vincentbernat** [comment]
How do you run `video2hls`? Make sure to use `python3.6 video2hls`. Otherwise, you end up using the default system Python which, in Xenial, is 3.5.

**Comment by andygr** [comment]
I am using Python 3.6.10...

user1@ubuntu:~# python -V
Python 3.6.10

**Comment by vincentbernat** [comment]
Then, can you run `video2hls` with `python video2hls` instead of just `./video2hls`.

**Comment by andygr** [comment]
Thank you, will try it
