### ISSUE TITLE
HLS encryption - AES 128

### ISSUE THREAD

**Issue by andygr** [vincentbernat/video2hls#6]
Hello,

I installed the latest ffmpeg and python 3.6.10 and worked as expected.

I have couple of questions:

1) Is there a plan to add as an option AES128 encryption?

2) If I want to use my own bitrates and resolutions, shall I use the following command?
how can I choose baseline and main profiles?

python video2hls 
            --video-bitrates 8000 4000 2000 1000 \ 
            --video-widths 1920 1920 1280 854 \
            --video-names '1080p high' '1080p low'
   TearsOfSteel.mp4 

Thanks

**Comment by vincentbernat** [comment]
1. No plan for me.
2. Use `--video-profiles`.

**Comment by andygr** [comment]
great thank you, worked as expected.

I have a bash script for AES and will give it a go 


Regards,
Andrew
